{
 "title": "API Observability",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "API Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Request Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Requests Per Second"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{http_status=~\"4..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "Error Rate 400(%)"
    },
    {
     "expr": "(sum(rate(http_requests_total{http_status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "Error Rate 500 (%)"
    }
   ]
  },
  {
   "title": "Service Latency Comparison",
   "type": "timeseries",
   "description": "Deposit vs Withdraw",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{endpoint=\"/deposit\"}[1m])) by (le))",
     "legendFormat": " Deposit P90"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{endpoint=\"/withdraw\"}[1m])) by (le))",
     "legendFormat": "Withdraw P90"
    }
   ]
  }
 ]
}