{
 "title": "Flask API Observability",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Service Latency Comparison",
   "type": "timeseries",
   "description": "Deposit vs Withdraw",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_time_seconds_bucket{endpoint=\"/deposit\"}[5m])) by (le))",
     "legendFormat": " deposit"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_time_seconds_bucket{endpoint=\"/withdraw\"}[5m])) by (le))",
     "legendFormat": "withdraw"
    }
   ]
  },
  {
   "title": "Request Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(response_time_seconds_sum[5m])) / sum(rate(response_time_seconds_count[5m]))",
     "legendFormat": "AVG"
    }
   ]
  }
 ]
}