global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'front'
    static_configs:
      - targets: ['front:5000']

  - job_name: 'core'
    static_configs:
      - targets: ['core:5001']    

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']